export const featuredProjects = [
  {
    title: "VenomPrecision",
    stacks: [
      "Ruby",
      "Ruby on Rails",
      "postgresql",
      "React",
      "Redux",
      "TailwindCss",
    ],
    img:'/venom.png',
    desc: "VenomPrecision is a website that lists paintball game products and accessories.User can sign in and create new product, delete a product, add reservations and so on.",
    liveLink: "https://velvety-genie-9ab88d.netlify.app/",
    sourceCode: "https://github.com/JakariaJishan/VenomPrecision-front-end",
  },
  {
    title: "Budget App",
    stacks: [
      "ruby",
      "ruby on rails",
      "postgresql",
      "rspec",
      "capybara",
      "cancancan",
      "tailwindcss",
    ],
    img:"/budget.png",
    desc: "Budget Buddy is a mobile web application where you can manage your budget: you have a list of transactions associated with a category, so that you can see how much money you spent and on what.",
    liveLink: "https://budget-buddy-573e.onrender.com/",
    sourceCode: "https://github.com/JakariaJishan/Budget-App",
  },
  {
    title: "Recipe App",
    stacks: ["ruby", "ruby on rails", "erb", "mvc", "rspec", "capybara"],
    img:"/RecipeApp.png",
    desc: "The Recipe app keeps track of all your recipes, ingredients, and inventory. It will allow you to save ingredients, keep track of what you have, create recipes, and generate a shopping list based on… ",
    liveLink: null,
    sourceCode: "https://github.com/JakariaJishan/Recipe-app",
  },
];

export const workingProjects = [
  {
    title: "Blog App",
    stacks: ["ruby", "ruby on rails", "postgresql", "rspec"],
    img:'/Blogror.png',
    desc: "Built with Ruby on Rails, this blog boasts a sleek and responsive design, allowing readers to easily navigate through its content",
    liveLink: null,
    sourceCode: "https://github.com/JakariaJishan/Blog-ror",
  },
  {
    title: "Catalog of Things",
    stacks: ["ruby", "postgresql", "rspec"],
    img:'/catelog.png',
    desc: "This project creates a console app that helps users keep track of their books, music albums, movies, and games.",
    liveLink: null,
    sourceCode: "https://github.com/JakariaJishan/Catalog-of-things",
  },
  {
    title: "School Library",
    stacks: ["ruby", "postgresql", "oop"],
    img:'/library.png',
    desc: "School Library is an app where record what books are in the library and who borrows them.",
    liveLink: null,
    sourceCode: "https://github.com/JakariaJishan/school-library",
  },
  {
    title: "Vet Clinic Database",
    stacks: ["database", "postgresql"],
    img:'/database.png',
    desc: "In this project, I use a relational database to create the initial data structure for a vet clinic. I create a table to store animals' information, insert some data into it, and query it.",
    liveLink: null,
    sourceCode: "https://github.com/JakariaJishan/Vet-clinic-database",
  },
  {
    title: "Anime List",
    stacks: ["react", "redux", "javascript"],
    img:'/anime.png',
    desc: "Anime List is a single page web application (SPA) built with React, Redux, Axios, and Jest, which shows a list of popular anime lists, and shows detailed information on anime counts..",
    liveLink: "https://anime-q544.onrender.com/",
    sourceCode: "https://github.com/JakariaJishan/anime-list",
  },
  {
    title: "Space Travelers Hub",
    stacks: ["react", "redux toolkit", "testing", "api", "webpack", "babel"],
    img:"/space.png",
    desc: "Space Traveler's Hub is a web application that displays SpaceX rockets and missions, users can join/leave missions or reserve/cancel rockets.",
    liveLink: "https://space-travelers-hub-qsa2.onrender.com/",
    sourceCode: "https://github.com/JakariaJishan/Space-Travelers-Hub",
  },
  {
    title: "ToDo",
    stacks: ["react", "react router dom"],
    img:"/todo.png",
    desc: "React ToDo is a webapp built with react js",
    liveLink: "https://react-todo-9vo7.onrender.com/",
    sourceCode: "https://github.com/JakariaJishan/react-todo",
  },
  {
    title: "Calculator",
    stacks: ["react", "react router dom"],
    img:"/calculator.png",
    desc: "Calculator is an app made with react and react router dome",
    liveLink: "https://react-calculator-n9d5.onrender.com/",
    sourceCode: "https://github.com/JakariaJishan/calculator-react",
  },
  {
    title: "Book Store",
    stacks: ["react", "react router dom"],
    img:"/bookstore.png",
    desc: "The Bookstore is a website similar to the 'Awesome Books' website . I create an simplified version of it that allows to: Display a list of books, Add a book, Remove a selected book By building this application.",
    liveLink: "https://react-book-store-v0z2.onrender.com/",
    sourceCode: "https://github.com/JakariaJishan/book-store",
  },
  {
    title: "Retro Watchers Capstone",
    stacks: ["javascript", "async-await"],
    img:"/retro.png",
    desc: "Javascript Capstone Project is a website based on an external API. It uses The Movie Db Api to get info about different characters, and Involvement API to store likes and comments from users.",
    liveLink: "https://chelobotix.github.io/Retro-Watchers-Capstone/dist/",
    sourceCode: "https://github.com/JakariaJishan/Retro-Watchers-Capstone",
  },
  {
    title: "Cryptico",
    stacks: ["html", "css", "javascript"],
    img:"/cryptico.png",
    desc: "Cryptico is the fastest and most secure Web3 platform that lets your team manage money and digital assets such as Bitcoin, Ethereum, Tether, and more.",
    liveLink: "https://jakariajishan.github.io/Capstone-1/",
    sourceCode: "https://github.com/JakariaJishan/Capstone-1",
  },
];
